### ISSUE TITLE
Нет возможности при прикреплении ссылки выбрать файл

### ISSUE THREAD

**Issue by alexsoin** [apnix/frontendeditor#2]
Если в админке через редактор при вставки ссылки можно выбрать файл на сервере и получить на него ссылку, то через фронтенд редактор нет такой возможности. Планируется ли в дальнейшем такую возможность добавить?

**Comment by apnix** [comment]
Да это было бы полезно. Как мне видится есть два пути как это сделать. Вызвать менеджер загрузки который используется в админке modx, но в таком случае придется грузить библиотеки extjs на фронт. Либо писать свой менеджер загрузки. Что лучше я так сходу затрудняюсь сказать. Как будет время я постараюсь разобраться и добавить эту возможность.

**Comment by apnix** [comment]
Добавлено в версии v1.2

**Comment by alexsoin** [comment]
![изображение](https://user-images.githubusercontent.com/3787132/95750062-a611ec00-0cad-11eb-9ef1-279a0c8d6996.png)
чтото пошло не так)))

**Comment by apnix** [comment]
Адрес админки стандартный /manager ?

**Comment by alexsoin** [comment]
Нет, измененный

**Comment by apnix** [comment]
Не предусмотрел такой вариант, поправлю сегодня.

**Comment by apnix** [comment]
Исправлено https://github.com/apnix/frontendeditor/releases/tag/v1.2.2
Адрес админки теперь берется из MODX_MANAGER_URL если там он прописан верно все должно работать.
